[Product]

ProductType = "Graph"
TotalWidth = "1500"
TotalHeight = "800"

[SubProduct 1]

GraphType = "Raster"
MainTitleString = "MHFD Backup (AWS) Server Disk Utilization (Hourly Maximum)"
LeftYAxisLegendPosition = "Left"
LegendFormat = "%S: %L"
LeftYAxisIgnoreUnits = "true"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"

[Data 1.1]

TSID = "ud-ns518b.Clients/CO-District-MHFD.'Filesystems: /: Space utilization-Max'.Hour"
SymbolTablePath = "example-heatmap-diskspace-utilization-symtable.csv"
