[Product]

ProductType = "Graph"
TotalWidth = "1500"
TotalHeight = "800"

[SubProduct 1]

GraphType = "Raster"
MainTitleString = "NovaStar Systems Memory Utilization (Hourly Maximum)"
LeftYAxisLegendPosition = "Left"
LegendFormat = "%S: %L"
LeftYAxisIgnoreUnits = "true"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
SymbolTablePath = "example-heatmap-memory-utilization-symtable.csv"

[Data 1.1]

TSID = "gc_novastar5a.Clients/AZ-County-Gila.'Memory: Utilization-Max'.Hour"

[Data 1.2]

TSID = "mc_novastar5d.Clients/AZ-County-Maricopa.'Memory: Utilization-Max'.Hour"

[Data 1.3]

TSID = "mc_novastar5a.Clients/AZ-County-Maricopa.'Memory: Utilization-Max'.Hour"

[Data 1.4]

TSID = "mc_novastar5b.Clients/AZ-County-Maricopa.'Memory: Utilization-Max'.Hour"

[Data 1.5]

TSID = "ypnovastar5a.Clients/AZ-County-Yavapai.'Memory: Utilization-Max'.Hour"

[Data 1.6]

TSID = "ypnovastar5b-stretch.Clients/AZ-County-Yavapai.'Memory: Utilization-Max'.Hour"

[Data 1.7]

TSID = "'novastar-prd-02.roseville.ca.us'.Clients/CA-City-Roseville.'Memory: Utilization-Max'.Hour"

[Data 1.8]

TSID = "ccnovastar5a.Clients/CA-County-ContraCosta.'Memory: Utilization-Max'.Hour"

[Data 1.9]

TSID = "'contracosta-ns5.trilynx-novastar.systems'.Clients/CA-County-ContraCosta.'Memory: Utilization-Max'.Hour"

[Data 1.10]

TSID = "PWNOVASTAR01.Clients/CA-County-LA.'Memory: Utilization-Max'.Hour"

[Data 1.11]

TSID = "PWNOVASTAR02.Clients/CA-County-LA.'Memory: Utilization-Max'.Hour"

[Data 1.12]

TSID = "ocnovastar5a.Clients/CA-County-Orange.'Memory: Utilization-Max'.Hour"

[Data 1.13]

TSID = "spkatenvlnx02.Clients/CA-County-Orange.'Memory: Utilization-Max'.Hour"

[Data 1.14]

TSID = "spkatenvlnx03.Clients/CA-County-Orange.'Memory: Utilization-Max'.Hour"

[Data 1.15]

TSID = "placerns5.Clients/CA-County-Placer.'Memory: Utilization-Max'.Hour"

[Data 1.16]

TSID = "FLOOD-81NOVAS01.Clients/CA-County-Riverside.'Memory: Utilization-Max'.Hour"

[Data 1.17]

TSID = "sanbernardino-primary.Clients/CA-County-SanBernardino.'Memory: Utilization-Max'.Hour"

[Data 1.18]

TSID = "'sanbernardino-iridium.trilynx-novastar.systems'.Clients/CA-County-SanBernardino.'Memory: Utilization-Max'.Hour"

[Data 1.19]

TSID = "pwgalert5-64.Clients/CA-County-SanBernardino.'Memory: Utilization-Max'.Hour"

[Data 1.20]

TSID = "socnovastar5-64.Clients/CA-County-Ventura.'Memory: Utilization-Max'.Hour"

[Data 1.21]

TSID = "socnovastar5b-64.Clients/CA-County-Ventura.'Memory: Utilization-Max'.Hour"

[Data 1.22]

TSID = "colx02.Clients/CA-District-CoachellaValley.'Memory: Utilization-Max'.Hour"

[Data 1.23]

TSID = "lv_novastar5a.Clients/CO-City-Loveland.'Memory: Utilization-Max'.Hour"

[Data 1.24]

TSID = "'larimerco-ns5.trilynx-novastar.systems'.Clients/CO-County-Larimer.'Memory: Utilization-Max'.Hour"

[Data 1.25]

TSID = "ud-ns518.Clients/CO-District-MHFD.'Memory: Utilization-Max'.Hour"

[Data 1.26]

TSID = "ud-ns518b.Clients/CO-District-MHFD.'Memory: Utilization-Max'.Hour"

[Data 1.27]

TSID = "flood1-64.Clients/CT-District-SCCRWA.'Memory: Utilization-Max'.Hour"

[Data 1.28]

TSID = "flood2-64.Clients/CT-District-SCCRWA.'Memory: Utilization-Max'.Hour"

[Data 1.29]

TSID = "nws-las-vegas.Clients/FED-NWS-LasVegas.'Memory: Utilization-Max'.Hour"

[Data 1.30]

TSID = "ati2.Clients/INT-Country-Jordan.'Memory: Utilization-Max'.Hour"

[Data 1.31]

TSID = "ati1.Clients/INT-Country-Jordan.'Memory: Utilization-Max'.Hour"

[Data 1.32]

TSID = "HYDRO-7.Clients/INT-Country-Panama.'Memory: Utilization-Max'.Hour"

[Data 1.33]

TSID = "HYDRO-8.Clients/INT-Country-Panama.'Memory: Utilization-Max'.Hour"

[Data 1.34]

TSID = "StLuciaNS5a.Clients/INT-Country-StLucia.'Memory: Utilization-Max'.Hour"

[Data 1.35]

TSID = "'novastar5-secondary.ccrfcd.org'.Clients/NV-County-Clark.'Memory: Utilization-Max'.Hour"

[Data 1.36]

TSID = "'novastar5-primary.ccrfcd.org'.Clients/NV-County-Clark.'Memory: Utilization-Max'.Hour"

[Data 1.37]

TSID = "'dcnovastar5.douglas.local'.Clients/NV-County-Douglas.'Memory: Utilization-Max'.Hour"

[Data 1.38]

TSID = "apfc06.Clients/TX-City-Dallas.'Memory: Utilization-Max'.Hour"

[Data 1.39]

TSID = "'dallas-cloud-ns5.trilynx-novastar.systems'.Clients/TX-City-Dallas.'Memory: Utilization-Max'.Hour"

[Data 1.40]

TSID = "APSDM01.Clients/TX-City-Dallas.'Memory: Utilization-Max'.Hour"

[Data 1.41]

TSID = "APSDM02.Clients/TX-City-Dallas.'Memory: Utilization-Max'.Hour"

[Data 1.42]

TSID = "NovaStar5-Main.Clients/TX-County-Hays.'Memory: Utilization-Max'.Hour"

[Data 1.43]

TSID = "HaysCountyAzure.Clients/TX-County-Hays.'Memory: Utilization-Max'.Hour"

[Data 1.44]

TSID = "hays-ns5-second.Clients/TX-County-Hays.'Memory: Utilization-Max'.Hour"

[Data 1.45]

TSID = "dallaswu_novastar_raid.Clients/TX-Utility-DallasWater.'Memory: Utilization-Max'.Hour"

[Data 1.46]

TSID = "jumpbox.Hardware/Dell.'Memory: Utilization-Max'.Hour"

[Data 1.47]

TSID = "hw-w32-ns5m-test01.'NovaStar Servers/32-bit'.'Memory: Utilization-Max'.Hour"

[Data 1.48]

TSID = "trilynx-aws-stretch.'NovaStar Servers/64-bit'.'Memory: Utilization-Max'.Hour"

[Data 1.49]

TSID = "'bridge-monitor.trilynx-novastar.systems'.'NovaStar Servers/64-bit'.'Memory: Utilization-Max'.Hour"

[Data 1.50]

TSID = "hw-j64-ns5m-test01.'NovaStar Servers/64-bit'.'Memory: Utilization-Max'.Hour"

[Data 1.51]

TSID = "'zabbix5-server.trilynx-novastar.systems'.TriLynx/AWS.'Memory: Utilization-Max'.Hour"

[Data 1.52]

TSID = "'zabbix5-web.trilynx-novastar.systems'.TriLynx/AWS.'Memory: Utilization-Max'.Hour"

[Data 1.53]

TSID = "'zabbix5-db.trilynx-novastar.systems'.TriLynx/AWS.'Memory: Utilization-Max'.Hour"

[Data 1.54]

TSID = "wet-novastar5-gcp2.WET/GCP.'Memory: Utilization-Max'.Hour"
