[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "MHFD CPU Utilization"

[SubProduct 1]

GraphType = "Line"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"

[Data 1.1]

TSID = "ud-ns518b.Clients/CO-District-MHFD.'CPU: utilization-Max'.Hour"
Color = "Red"

[Data 1.2]

TSID = "ud-ns518b.Clients/CO-District-MHFD.'CPU: utilization-Avg'.Hour"
Color = "DarkGray"

[Data 1.3]

TSID = "ud-ns518b.Clients/CO-District-MHFD.'CPU: utilization-Min'.Hour"

[Data 1.4]

TSID = "ud-ns518b.Clients/CO-District-MHFD.'CPU: utilization'.IrregSecond"
Color = "Blue"
