[Product]

ProductType = "Graph"
TotalWidth = "1500"
TotalHeight = "800"

[SubProduct 1]

GraphType = "Raster"
MainTitleString = "NovaStar Systems Disk Utilization (Hourly Maximum)"
LeftYAxisLegendPosition = "Left"
LegendFormat = "%S: %L"
LeftYAxisIgnoreUnits = "true"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
SymbolTablePath = "example-heatmap-diskspace-utilization-symtable.csv"

[Data 1.1]

TSID = "ypnovastar5a.Clients/AZ-County-Yavapai.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.2]

TSID = "ypnovastar5b-stretch.Clients/AZ-County-Yavapai.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.3]

TSID = "'novastar-prd-02.roseville.ca.us'.Clients/CA-City-Roseville.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.4]

TSID = "ccnovastar5a.Clients/CA-County-ContraCosta.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.5]

TSID = "'contracosta-ns5.trilynx-novastar.systems'.Clients/CA-County-ContraCosta.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.6]

TSID = "PWNOVASTAR01.Clients/CA-County-LA.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.7]

TSID = "PWNOVASTAR02.Clients/CA-County-LA.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.8]

TSID = "ocnovastar5a.Clients/CA-County-Orange.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.9]

TSID = "placerns5.Clients/CA-County-Placer.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.10]

TSID = "socnovastar5-64.Clients/CA-County-Ventura.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.11]

TSID = "socnovastar5b-64.Clients/CA-County-Ventura.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.12]

TSID = "colx02.Clients/CA-District-CoachellaValley.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.13]

TSID = "'larimerco-ns5.trilynx-novastar.systems'.Clients/CO-County-Larimer.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.14]

TSID = "ud-ns518.Clients/CO-District-MHFD.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.15]

TSID = "ud-ns518b.Clients/CO-District-MHFD.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.16]

TSID = "ati2.Clients/INT-Country-Jordan.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.17]

TSID = "ati1.Clients/INT-Country-Jordan.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.18]

TSID = "HYDRO-7.Clients/INT-Country-Panama.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.19]

TSID = "HYDRO-8.Clients/INT-Country-Panama.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.20]

TSID = "StLuciaNS5a.Clients/INT-Country-StLucia.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.21]

TSID = "'dallas-cloud-ns5.trilynx-novastar.systems'.Clients/TX-City-Dallas.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.22]

TSID = "dallaswu_novastar_raid.Clients/TX-Utility-DallasWater.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.23]

TSID = "jumpbox.Hardware/Dell.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.24]

TSID = "hw-w32-ns5m-test01.'NovaStar Servers/32-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.25]

TSID = "'novastar5-secondary.ccrfcd.org'.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.26]

TSID = "apfc06.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.27]

TSID = "'dcnovastar5.douglas.local'.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.28]

TSID = "'novastar5-primary.ccrfcd.org'.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.29]

TSID = "nws-las-vegas.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.30]

TSID = "APSDM01.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.31]

TSID = "APSDM02.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.32]

TSID = "trilynx-aws-stretch.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.33]

TSID = "mc_novastar5d.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.34]

TSID = "sanbernardino-primary.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.35]

TSID = "NovaStar5-Main.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.36]

TSID = "flood1-64.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.37]

TSID = "'sanbernardino-iridium.trilynx-novastar.systems'.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.38]

TSID = "'bridge-monitor.trilynx-novastar.systems'.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.39]

TSID = "mc_novastar5a.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.40]

TSID = "mc_novastar5b.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.41]

TSID = "flood2-64.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.42]

TSID = "gc_novastar5a.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.43]

TSID = "lv_novastar5a.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.44]

TSID = "HaysCountyAzure.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.45]

TSID = "spkatenvlnx02.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.46]

TSID = "hw-j64-ns5m-test01.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.47]

TSID = "wet-novastar5-gcp2.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.48]

TSID = "pwgalert5-64.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.49]

TSID = "hays-ns5-second.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.50]

TSID = "FLOOD-81NOVAS01.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.51]

TSID = "spkatenvlnx03.'NovaStar Servers/64-bit'.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.52]

TSID = "'zabbix5-server.trilynx-novastar.systems'.TriLynx/AWS.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.53]

TSID = "'zabbix5-web.trilynx-novastar.systems'.TriLynx/AWS.'Filesystems: /: Space utilization-Max'.Hour"

[Data 1.54]

TSID = "'zabbix5-db.trilynx-novastar.systems'.TriLynx/AWS.'Filesystems: /: Space utilization-Max'.Hour"
