[Product]

ProductType = "Graph"
TotalWidth = "1500"
TotalHeight = "800"
MainTitleString = "CPU Utilization (Hourly Max)"

[SubProduct 1]

GraphType = "Raster"
LeftYAxisTitleString = ""
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

[Data 1.1]

TSID = "wet-novastar5-gcp2.NovaStar Servers/64-bit.'CPU: utilization-Max'.Hour~Zabbix-trilynx"
SymbolTablePath = "example-cpu-utilization-wet-heatmap-symtable.csv"
