[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "MHFD NovaStar Servers"
SubTitleString = "CPU Utilization (%)"

[SubProduct 1]

GraphType = "Line"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"

[Data 1.1]

TSID = "ud-ns518b.Clients/CO-District-MHFD.'CPU: utilization-Avg'.Hour~Zabbix-trilynx"
Color = "Red"

[Data 1.2]

TSID = "ud-ns518b.Clients/CO-District-MHFD.'CPU: utilization'.IrregSecond~Zabbix-trilynx"
Color = "Red"

[Data 1.3]

TSID = "UD-NS518.Clients/CO-District-MHFD.'CPU: utilization-Avg'.Hour~Zabbix-trilynx"
Color = "Blue"

[Data 1.4]

TSID = "UD-NS518.Clients/CO-District-MHFD.'CPU: utilization'.IrregSecond~Zabbix-trilynx"
Color = "Blue"
