# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Open Water Foundation / TSTool Zabbix Plugin
nav:
- Home: index.md
- Introduction: introduction/introduction.md
- Getting Started: getting-started/getting-started.md
- Examples of Use: examples/examples.md
- Troubleshooting: troubleshooting/troubleshooting.md
- Reference - Commands:
  - Overview: command-ref/overview.md
  - ReadZabbix: command-ref/ReadZabbix/ReadZabbix.md
  - TSID: command-ref/TSID/TSID.md
- Reference - Datastores:
  - Overview: datastore-ref/overview.md
  - Zabbix Web Services: datastore-ref/Zabbix/Zabbix.md
- 'Appendix - Release Notes': appendix-release-notes/release-notes.md
- 'Appendix - Install Plugin': appendix-install/install.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright Open Water Foundation
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# ------------------------------------------------
# Favicon is supposed to automatically be found:
# - in docs/img/favicon.ico
# - is a copy of docs/images/OWF-Logo-Favicon-32x32.ico
# - instead, with Material them, have a different approach (see "theme" below)
# ------------------------------------------------
# Don't enable the repo URL because irritating edit icons are shown when editing really isn't allowed
#repo_url:  https://github.com/OpenWaterFoundation/cdss-app-tstool-doc-user
# ------------------------------------------------
site_author:  Open Water Foundation
site_description:  TSTool Zabbix Plugin
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  favicon: 'images/favicon.ico'
# ------------------------------------------------
# The following controls how URLs are created
# - As of MkDocs 1.0 the default is true meaning URLs to a page ABC is ABC/ rather than something/ABC.html.
# - see:  https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
# use_directory_urls: true
# ------------------------------------------------
